"""
Q_rxn inference from calibrated model parameters and experiment data.
Two methods:
  - 'ode': pointwise inversion of the reactor energy balance (ODE-based)
  - 'direct': direct jacket heat balance using T_jin, T_jout, and flow rate
"""
from __future__ import annotations
from typing import Optional
import numpy as np
from scipy.signal import savgol_filter
from scipy.integrate import cumulative_trapezoid

from models import ModelParams, Cr, UA_rj


def _central_diff(t: np.ndarray, y: np.ndarray) -> np.ndarray:
    """Central finite differences with forward/backward at boundaries."""
    dt = np.diff(t)
    dydx = np.empty_like(y)
    dydx[1:-1] = (y[2:] - y[:-2]) / (t[2:] - t[:-2])
    dydx[0]  = (y[1] - y[0]) / dt[0]
    dydx[-1] = (y[-1] - y[-2]) / dt[-1]
    return dydx


def _smooth(arr: np.ndarray, window: int) -> np.ndarray:
    """Savitzky-Golay smoothing. window=0 means no smoothing."""
    if window < 3:
        return arr.copy()
    w = window if window % 2 == 1 else window + 1
    w = min(w, len(arr) if len(arr) % 2 == 1 else len(arr) - 1)
    if w < 3:
        return arr.copy()
    return savgol_filter(arr, window_length=w, polyorder=2)


def infer_Q_rxn_pointwise(
    t: np.ndarray,
    T_r: np.ndarray,
    T_j: np.ndarray,
    T_amb: np.ndarray,
    mdot_cpf: np.ndarray,
    T_jin: np.ndarray,
    Q_calib: np.ndarray,
    params: ModelParams,
    smoothing_window: int = 11,
) -> np.ndarray:
    """
    Invert the reactor energy balance pointwise:
      Q_rxn = C_r(T_r) * dT_r/dt - Q_stir
              - UA_rj(T_r,T_j)*(T_j - T_r)
              - UA_loss*(T_amb - T_r)
              - Q_calib
    """
    T_r_smooth = _smooth(T_r, smoothing_window)
    T_j_smooth = _smooth(T_j, smoothing_window)

    dTr_dt = _central_diff(t, T_r_smooth)

    cr = Cr(T_r_smooth, params.ca0, params.ca1)
    cr = np.maximum(cr, 1.0)

    ua = UA_rj(T_r_smooth, T_j_smooth, params.ka0, params.ka1, params.ka2)
    ua = np.maximum(ua, 0.0)

    Q_rxn = (cr * dTr_dt
             - params.Q_stir
             - ua * (T_j_smooth - T_r_smooth)
             - params.ka3 * (T_amb - T_r_smooth)
             - Q_calib)
    return Q_rxn


def direct_heat_balance(
    t: np.ndarray,
    T_r: np.ndarray,
    T_jout: np.ndarray,
    T_jin: np.ndarray,
    T_amb: np.ndarray,
    mdot_cpf: np.ndarray,
    C_r_eff: float,
    UA_loss: float,
    Q_stir: float,
    Q_calib: np.ndarray,
    smoothing_window: int = 11,
) -> np.ndarray:
    """
    Direct jacket heat balance:
      Q_rxn = C_r_eff * dT_r/dt
              + m_dot*cp*(T_jout - T_jin)
              + UA_loss*(T_r - T_amb)
              - Q_stir
              - Q_calib

    Positive Q_rxn = exothermic (heat generated by reaction).
    """
    T_r_smooth = _smooth(T_r, smoothing_window)
    dTr_dt = _central_diff(t, T_r_smooth)

    Q_rxn = (C_r_eff * dTr_dt
             + mdot_cpf * (T_jout - T_jin)
             + UA_loss * (T_r_smooth - T_amb)
             - Q_stir
             - Q_calib)
    return Q_rxn


def compute_metrics(
    t: np.ndarray,
    Q_rxn: np.ndarray,
    T_r_sim: Optional[np.ndarray] = None,
    T_r_meas: Optional[np.ndarray] = None,
) -> dict:
    """Compute key performance metrics from Q_rxn timeseries."""
    cumulative = cumulative_trapezoid(Q_rxn, t, initial=0.0)
    total_energy_J = float(cumulative[-1])

    peak_Q = float(np.max(np.abs(Q_rxn)))
    peak_idx = int(np.argmax(np.abs(Q_rxn)))
    peak_t = float(t[peak_idx])

    # Reaction duration: time where |Q_rxn| > 5% of peak
    threshold = 0.05 * peak_Q
    active = np.abs(Q_rxn) > threshold
    if active.any():
        duration_s = float(t[active][-1] - t[active][0])
    else:
        duration_s = 0.0

    metrics: dict = {
        "cumulative_energy_J": total_energy_J,
        "cumulative_energy_kJ": total_energy_J / 1000.0,
        "peak_Q_rxn_W": float(np.max(Q_rxn)),
        "min_Q_rxn_W": float(np.min(Q_rxn)),
        "peak_abs_Q_rxn_W": peak_Q,
        "peak_t_s": peak_t,
        "reaction_duration_s": duration_s,
        "reaction_duration_min": duration_s / 60.0,
    }

    if T_r_sim is not None and T_r_meas is not None:
        rng = float(T_r_meas.max() - T_r_meas.min())
        if rng > 1e-6:
            nrmse = float(np.sqrt(np.mean((T_r_sim - T_r_meas) ** 2)) / rng)
        else:
            nrmse = 0.0
        metrics["nrmse_Tr"] = nrmse
    else:
        metrics["nrmse_Tr"] = None

    return metrics
